<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDeUKOXt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDeUKOXt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDeUKOXt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDeUKOXt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDeUKOXt\App_KernelDevDebugContainer([
    'container.build_hash' => 'DeUKOXt',
    'container.build_id' => 'd80ec5f0',
    'container.build_time' => 1637016015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDeUKOXt');
