<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'course_index' => [[], ['_controller' => 'App\\Controller\\CourseController::index'], [], [['text', '/courses/']], [], []],
    'course_show' => [['courseId'], ['_controller' => 'App\\Controller\\CourseController::show'], [], [['variable', '/', '[^/]++', 'courseId', true], ['text', '/courses']], [], []],
    'course_create' => [[], ['_controller' => 'App\\Controller\\CourseController::create'], [], [['text', '/courses/']], [], []],
    'course_update' => [['courseId'], ['_controller' => 'App\\Controller\\CourseController::update'], [], [['variable', '/', '[^/]++', 'courseId', true], ['text', '/courses']], [], []],
    'course_delete' => [['courseId'], ['_controller' => 'App\\Controller\\CourseController::delete'], [], [['variable', '/', '[^/]++', 'courseId', true], ['text', '/courses']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
